server.port=8081

spring.kafka.bootstrap-servers=127.0.0.1:9092
#spring.kafka.consumer.group-id=myGroup


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-serializer=org.apache.kafka.common.serialization.JsonDeserializer
kafka.consumer.topic.name.create-order=local-cluster

# Máximo de mensagens que serão retornadas por poll
spring.kafka.consumer.properties.max.poll.records=1000

# Aumenta o número máximo de bytes permitidos por fetch (aqui: 50MB)
spring.kafka.consumer.properties.fetch.max.bytes=52428800

# Tempo máximo (em milissegundos) que o broker vai esperar antes de retornar os dados, mesmo que não tenha alcançado o tamanho mínimo
spring.kafka.consumer.properties.fetch.max.wait.ms=300

# Define o tamanho mínimo de bytes que o broker deve acumular antes de enviar uma resposta ao consumidor
spring.kafka.consumer.properties.fetch.min.bytes=50000

